### PR TITLE
Daniel/vscode devcontainer config

### PR DESCRIPTION
**Pull request by dandanlen**
This contains the container setup and the corresponding explanation as part of a README file. 

Please check if the instructions work on your machine with this container setup.

### CODE REVIEW

**Comment by dandanlen** [comment]
No... it works on my machine 😅 

I'll take a look.

**Comment by dandanlen** [comment]
Hey, 

I tried deleting all of my docker images and containers and regenerating everything from scratch and it still works for me... 

How exactly are you starting the project? (Via the vscode debugger? From the container's command line? ... again, both seem to work for me) Can you also let me know what version of vs code you are using? Mine is:

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

Thanks

**Comment by AndreiBozantan** [comment]
I tried this and it works fine for me (it took several minutes to build the Docker image initially).

**Comment by sebastian** [comment]
Ok, seems to work for me too I think... hm. It was complaining something about the OmniSharp stuff, but well, I can still edit code and get warnings etc. So I guess it is actually working after all.

**Comment by sebastian** [comment]
Well, I am strictly speaking seeing the same error output as above still... but yeah, I guess it does work.
As to version info:

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

**Comment by sebastian** [comment]
Aha, you are running a version of macOS from the stone age, @dandanlen?
From my version on-wards they are doing some magic with read only partitions on disk, maybe it's interfering somehow?
The fallback package folder it is complaining about is not existing though, and the directory is read only. Maybe that is the cause? Either way things seem to work. I am wondering why it is trying to write anything to my macOS filesystem anyway? Shouldn't the writing be restricted to inside the container?

**Comment by dandanlen** [comment]
You're right, I haven't been very diligent with my OS updates... It should be writing inside the container, yes, but the fallback folder doesn't exist on the container. Maybe because the volume is being mapped from a readonly parition... but this is a strange one, the whole point of containers is to make sure there are no differences, Docker should take care of this. 

What is your Docker version? Mine is Version `2.1.0.3`. (I'm almost up to date here at least 😅 )

**Comment by sebastian** [comment]
My docker version is:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by dandanlen** [comment]
Ok thanks, pretty much the the same.  My full version info is: 

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Do you have docker desktop installed (That's what my 2.1.0.3 referred to btw.)? The VS Code documentation mentions Docker Desktop specifically - although I don't see why this would make any difference.

**Comment by dandanlen** [comment]
Ok, then I guess macOS must be the culprit... I'll update my OS tonight and see if that breaks things.

**Comment by sebastian** [comment]
oh my, that's risky business! It will undoubtedly break more things than you would like!
If this both works for you, then I suggest we move forward for now and look for a fix down the line. 
After all getting some functionality in place is higher prio.

**Comment by dandanlen** [comment]
haha yes agreed - tracking down obscure mac OS regressions can wait 👍

**Comment by sebastian** [comment]
In that case I guess we'll just have to wait for @AndreiBozantan to accept this pull request.

**Pull request merged**
